# Site settings
title: Umang Desai's CV 
description: ddbullfrog's CV
favicon: /assets/img/avatar.JPG
baseurl: 
url: http://localhost.com:4000
rss_url: 
google_analytics: 

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Umang Desai
  title: Software Engineer
  address: California, USA 
  email: umangd03@gmail.com
  link: http://umangdesai.com
  weibo:
  github: umang-desai
  linkedin: umangdesai
  twitter: umanglfc
  gavatar: /assets/img/avatar.JPG
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1: 
      company: George Mason Univ. Department of Computer Science
      location: Fairfax, USA
      title: Teaching Assistant
      started: 2017
      duration: (2017 - 2018)
      description: Software Engineering:<br> • Conducting lectures and presentations. <br> • Grading deliverables for a full scale SDLC project, assignments, presentation peer evaluations. <br> • Mentoring students on different stages of SDLC and conducting bi-weekly meetings for project review, enabling AGILE culture.    <br><br>Object Oriented Programming:<br>• Mentoring undergraduates through office hours, teaching students of varying level of understanding the concepts of Java Object Oriented Programming.<br>• Conducting lectures and programming labs.<br>• Grading assignments, labs, projects.

    - work2:
      company: Matreya.IO
      location: NYC, USA
      title: Blockchain Developer
      started: 2017
      duration: (June 2017 -  Aug 2017)
      description: • Develop and review high level design for the BlockChain. Also, find possible implementation solutions for Proof of Space(PoS). <br>• Optimize Proof of Work algorithm for x86.<br>• Modify difficulty adjustment algorithm to DigiByte v3.0.<br>• Designed and tested unit tests for DAA and PoW algorithms.

    - work3:
      company: Fondo
      location: Mumbai, India
      title: Co-Founder
      started: 2015
      duration: (2015 - 2016)
      description: • Social event discovery application to correlate user and events geospatial data and indicate suitable local events for a user. <br> • Designing and developing backend, databases and data-models. <br> • Maintain, monitor and review development of the application and manage project deadlines. <br> • Actively involved in software architecture and product development.

    - work4:
      company: ESQ Business Services
      location: Cupertino, USA
      title: Software Engineer
      started: 2012
      duration: (2012 - 2014)
      description: • Designed, developed and tested module to monitor JVM on a host by extracting telemetry data using JAVA, MSSQL and JMX. This was achieved via a 3 tier client-server-data backend architecture. <br> • Designed and modeled a database for the data extracted. Then developed advanced filtering across multiple Mbeans for retrieving these metrics for bandwidth friendly data pipelines. <br> • Configured frameworks like XStream for configuration files and models, log4j for logging. <br> • Designed, developed and tested module to monitor Linux via the proc fs to analyze system performance and uptime. This was achieved with JAVA and MSSQL. <br> • Developed a parsing framework for system proc files with configurable polling mechanisms.

  educationHistory:
    - education1:
      organization: Pennsylvania State University
      location: Pennsylvania, USA
      degree: BS
      major: Information Technology
      started: 2010
      duration: (2010 - 2012)
      description: 

    - education2:
      organization: George Mason University
      location: Virginia, USA
      degree: MS
      major: Computer Science
      started: 2016
      duration: (2016 - 2018)
      description: 

  languages:
    - language1:
      name: English
      proficiency: Native
    - language2:
      name: Hindi
      proficiency: Native
    - language3:
      name: Gujurati
      proficiency: Native

  programmingSkills:
    - skill1:
      name: Java/ Java EE
      percentage: 90%
    - skill2:
      name: C
      percentage: 70%
    - skill3:
      name: C++
      percentage: 50%
    - skill4: 
      name: Sql
      percentage: 70%
    - skill5:
      name: Python
      percentage: 30%
